CREATE TABLE PRODUCT 
(
	PRODUCT_WK		    INTEGER			NOT NULL	PRIMARY KEY,
	PRODUCT_ID      	NVARCHAR(50)	NOT NULL,
	NAME            	NVARCHAR(50)	NOT NULL,
	CATEGORY		    NVARCHAR(50)    NOT NULL,
	SUB_CATEGORY        NVARCHAR(50)    NOT NULL,
	PRODUCT_DESCRIPTION	NVARCHAR(50)	NOT NULL,	
	UNIT_SELL_PRICE		FLOAT		    NOT NULL,
	CURRENCY        	NVARCHAR(20)	NOT NULL
);

CREATE TABLE CUSTOMER
(
	CUSTOMER_WK		INTEGER			NOT NULL	PRIMARY KEY,
	CUSTOMER_ID     INTEGER     	NOT NULL,
	NAME            NVARCHAR(100)	NOT NULL,
	PHONE		    NVARCHAR(50)    NOT NULL,
	EMAIL           NVARCHAR(50)    NOT NULL
);

CREATE TABLE WAREHOUSE
(
	WAREHOUSE_WK	    INTEGER			NOT NULL	PRIMARY KEY,
	WAREHOUSE_ID        NVARCHAR(50)   	NOT NULL,
	WAREHOUSE_NAME      NVARCHAR(50)	NOT NULL,
	LOCATION            NVARCHAR(50)    NOT NULL
);

CREATE TABLE DATE 
(
	Day_WK		        INTEGER			NOT NULL	PRIMARY KEY,
	Month_WK	        INTEGER			NOT NULL,
	FullDate	        DATE			NOT NULL,
    Year_Code	        INTEGER			NOT NULL,
    Month_Code	        INTEGER			NOT NULL,
    Month_Name	        NVARCHAR(20)	NOT NULL,
    Weekday_Code        INTEGER			NOT NULL,
    Day_Name	        NVARCHAR(20)	NOT NULL,
    Is_Weekday          INTEGER			NOT NULL,
    NumberOfWoekDays    INTEGER			NOT NULL
);

CREATE TABLE ADDRESS
(
	ADDRESS_WK	        INTEGER			NOT NULL	PRIMARY KEY,
	ADDRESS_LINE_1      NVARCHAR(50)    NOT NULL,
    ADDRESS_LINE_2      NVARCHAR(50)   	NOT NULL,
	CITY                INTEGER         NOT NULL,
    STATE               NVARCHAR(50)    NOT NULL,
    COUNTRY             NVARCHAR(50)   	NOT NULL,
    ZIPCODE             NVARCHAR(50)    NOT NULL,
    ADDRESS_TYPE        NVARCHAR(50)   	NOT NULL,
);

CREATE TABLE CUST_ADDRESS
(
	CUSTOMER_WK	            INTEGER			FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_WK),
	ADDRESS_WK	            INTEGER			FOREIGN KEY REFERENCES ADDRESS(ADDRESS_WK),
    CUSTOMER_ADDRESS_TYPE   NVARCHAR(50)   	NOT NULL
);

CREATE TABLE STOCK_FACT
(
	WAREHOUSE_WK    INTEGER		FOREIGN KEY REFERENCES WAREHOUSE(WAREHOUSE_WK),
	PRODUCT_WK	    INTEGER		FOREIGN KEY REFERENCES PRODUCT(PRODUCT_WK),
    TOTAL_STOCK     INTEGER   	NOT NULL,
    REORDER_POINT   INTEGER	    NOT NULL,
    STOCK_REMAIN    INTEGER		NOT NULL,
	STOCK_DATE_WK   INTEGER		FOREIGN KEY REFERENCES DATE(Day_WK),
    IS_RESTOCK      CHAR(1)     NOT NULL
);

CREATE TABLE ORDER_FACT
(
	CUSTOMER_WK     INTEGER		FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_WK),
	PRODUCT_WK	    INTEGER		FOREIGN KEY REFERENCES PRODUCT(PRODUCT_WK),
    REORDER_POINT   INTEGER	    NOT NULL,
    STOCK_REMAIN    INTEGER		NOT NULL,
	ORDER_DATE      INTEGER		FOREIGN KEY REFERENCES DATE(Day_WK)
);